# Generated by Django 4.2.7 on 2024-02-12 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_userprofile_session_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='PodLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('pod_name', models.CharField(max_length=255)),
                ('logs', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
